import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner"; // <-- Import Toaster

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scrap Seller",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* HEADER */}
            <Header />

            <main className="min-h-screen">{children}</main>

            {/* FOOTER */}
            <footer className="bg-muted/50 py-12 !mt-10">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made By Sayali Patil</p>
              </div>
            </footer>

            {/* TOAST NOTIFICATIONS */}
            <Toaster position="top-center" richColors /> {/* <- Add this */}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
